name: Ping Production

on:
  schedule:
    - cron: "0 17 * * *"

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Production Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.PRODUCTION_URL }}